### PR TITLE
taking into account color camera

### PR DESCRIPTION
**Pull request by seb5g**
trying to stabilize execution but not much success so far. The waiting version is even worse...

### CODE REVIEW

**Comment by seb5g** [comment]
Hi Romain, I updated your plugn to take into account the color cameras. That part is fine, but I needed to do a PR on pylablib to get the sensor info (monochrome or color). 
However, the overall stability is quite bad. I often encounter timeout errors or other errors. I'm using the zelux camera. Do you have similar issues?

**Comment by rgeneaux** [comment]
Hi,
I haven't tested enough in v4 yet (the stuff with ROIselect needs to be changed), but in v3 we have no issue with the plugin. 
Our zelux actually measures a fringe pattern for PID stabilization and it runs for hours everyday without issue.

perhaps you can try in pymodaq==3.6.13 and pymodaq_plugins_thorlabs==0.3.0, check if this you still have these issues? this way we might identify what's wrong

**Comment by rgeneaux** [comment]
Or do you mean that this new commit causes the unstability?

**Comment by seb5g** [comment]
well I used it before hand on a kiralux monochrome one, without issues. When I switched to the zelux (before I modified the content for color stuff) it was still very unstable. Do you use a long exposure time?

**Comment by rgeneaux** [comment]
Usually a few milliseconds, and we crop the sensor to get good FPS (~100)

**Comment by seb5g** [comment]
Actually it was the usb port I was using that caused the instability. Directly pluging the camera on the computer solved the issue. What should we do concerning this PR that need an update of pylablib? For the time being we could just let the user specify manually the sensor type...

**Comment by seb5g** [comment]
By the way you could probably achieve higher fps if you use the hardware live mode: http://pymodaq.cnrs.fr/en/pymodaq-dev/developer_folder/instrument_plugins.html#live-mode

**Pull request merged**
